# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Johnny Hong
tagline:             
description:         The presonal website of Johnny Hong
url:                 http://jcyhong.github.io
paginate:            1
baseurl:             ""
future:              true
# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Johnny Hong
  url:               
  email:             jcyhong@berkeley.edu

# Custom vars
version:             1.0.0
github:
  repo:              github.com/jcyhong/jcyhong.github.io

# List of pages
pages_list:          {'Home':'/home','Resume':'/resume','Research/Projects':'/research','Coursework':'/coursework','Teaching':'/teaching','Miscellaneous':'/miscellaneous'}

